{{- if .Values.pdb.create }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "agent-load-balancer.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "agent-load-balancer.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "agent-load-balancer.selectorLabels" . | nindent 6 }}
  {{- if .Values.pdb.minAvailable }}
  minAvailable: {{ .Values.pdb.minAvailable }}
  {{- else }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  {{- end }}
{{- end }}
